import pino, { type DestinationStream, type Logger } from "pino";

const REDACTED_PATHS = [
  "password",
  "privateKey",
  "private_key",
  "mnemonic",
  "seed",
  "WALLET_ENCRYPTION_KEY",
  "APPROVER_PRIVATE_KEY",
  "TESTNET_FUNDING_PRIVATE_KEY",
  "OPERATIONS_PRIVATE_KEY",
  "IRB_TOKEN_OWNER_PRIVATE_KEY",
  "encryptedPrivateKey",
  "encrypted_private_key",
  "rawTransaction",
  "raw_transaction",
  "signedTransaction",
  "signed_transaction",
  "ciphertext",
  "encryptionIv",
  "encryption_iv",
  "encryptionAuthTag",
  "encryption_auth_tag",
  "rpcUrl",
  "primaryUrl",
  "secondaryUrl",
  "authorization",
  "*.password",
  "*.privateKey",
  "*.private_key",
  "*.mnemonic",
  "*.seed",
  "*.WALLET_ENCRYPTION_KEY",
  "*.APPROVER_PRIVATE_KEY",
  "*.TESTNET_FUNDING_PRIVATE_KEY",
  "*.OPERATIONS_PRIVATE_KEY",
  "*.IRB_TOKEN_OWNER_PRIVATE_KEY",
  "*.encryptedPrivateKey",
  "*.encrypted_private_key",
  "*.rawTransaction",
  "*.raw_transaction",
  "*.signedTransaction",
  "*.signed_transaction",
  "*.ciphertext",
  "*.encryptionIv",
  "*.encryption_iv",
  "*.encryptionAuthTag",
  "*.encryption_auth_tag",
  "*.rpcUrl",
  "*.primaryUrl",
  "*.secondaryUrl",
  "config.database.password",
  "config.walletEncryption.key",
  "config.funding.privateKey",
  "config.authorization.approverPrivateKey",
  "config.campaignExecution.adminPrivateKey",
  "config.campaignExecution.operationsPrivateKey",
  "config.campaignExecution.irbTokenOwnerPrivateKey",
  "config.rpc.primaryUrl",
  "config.rpc.secondaryUrl",
  "req.headers.authorization",
  "headers.authorization",
] as const;

export function createLogger(
  level: string = process.env.LOG_LEVEL ?? "info",
  destination?: DestinationStream,
): Logger {
  return pino(
    {
      base: null,
      level,
      redact: {
        censor: "[REDACTED]",
        paths: [...REDACTED_PATHS],
      },
      timestamp: pino.stdTimeFunctions.isoTime,
    },
    destination,
  );
}
