CREATE TABLE reward_wallet_funding_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  wallet_id BIGINT UNSIGNED NOT NULL,
  wallet_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  network_chain_id INT UNSIGNED NOT NULL,
  balance_before_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_balance_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  funding_amount_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  funding_wallet_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tx_nonce BIGINT UNSIGNED NULL,
  gas_limit VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  signed_tx_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NULL,
  broadcast_tx_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NULL,
  block_number BIGINT UNSIGNED NULL,
  gas_used VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  effective_gas_price_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  fee_paid_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  balance_after_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('PLANNED','SIGNED','BROADCAST','CONFIRMED','SKIPPED','FAILED','PENDING_REVIEW') NOT NULL,
  status_reason VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_message VARCHAR(512) NULL,
  receipt_json JSON NULL,
  broadcast_at TIMESTAMP(6) NULL,
  confirmed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  active_wallet_id BIGINT UNSIGNED GENERATED ALWAYS AS (
    CASE WHEN status IN ('SIGNED','BROADCAST','PENDING_REVIEW') THEN wallet_id ELSE NULL END
  ) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_reward_wallet_funding_jobs_job_id (job_id),
  UNIQUE KEY uq_reward_wallet_funding_jobs_active_wallet (active_wallet_id),
  KEY idx_reward_wallet_funding_jobs_wallet_id (wallet_id),
  KEY idx_reward_wallet_funding_jobs_wallet_address (wallet_address),
  KEY idx_reward_wallet_funding_jobs_status (status),
  KEY idx_reward_wallet_funding_jobs_broadcast_hash (broadcast_tx_hash),
  CONSTRAINT fk_reward_wallet_funding_jobs_wallet
    FOREIGN KEY (wallet_id) REFERENCES reward_user_wallets (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
