CREATE TABLE reward_authorization_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  wallet_id BIGINT UNSIGNED NOT NULL,
  claimant_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  campaign_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_nonce VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  valid_after BIGINT UNSIGNED NOT NULL,
  deadline BIGINT UNSIGNED NOT NULL,
  approver_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  typed_data_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NULL,
  approver_signature VARCHAR(132) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('PLANNED','SIGNED','READY','CONSUMED','EXPIRED','CANCELLED','FAILED') NOT NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_message VARCHAR(512) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  signed_at TIMESTAMP(6) NULL,
  consumed_at TIMESTAMP(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_reward_authorization_jobs_job_id (job_id),
  UNIQUE KEY uq_reward_authorization_jobs_reward_id (reward_id),
  UNIQUE KEY uq_reward_authorization_jobs_nonce (campaign_id, claimant_address, reward_nonce),
  KEY idx_reward_authorization_jobs_wallet_id (wallet_id),
  KEY idx_reward_authorization_jobs_campaign_id (campaign_id),
  KEY idx_reward_authorization_jobs_status (status),
  CONSTRAINT fk_reward_authorization_jobs_wallet
    FOREIGN KEY (wallet_id) REFERENCES reward_user_wallets (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
