CREATE TABLE reward_claim_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  authorization_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  wallet_id BIGINT UNSIGNED NOT NULL,
  claimant_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  campaign_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_nonce VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tx_nonce BIGINT UNSIGNED NOT NULL,
  gas_limit VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  gas_price_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  signed_tx_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  broadcast_tx_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NULL,
  block_number BIGINT UNSIGNED NULL,
  gas_used VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  effective_gas_price_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  fee_paid_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  irb_balance_before VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  irb_balance_after VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reward_contract_balance_before VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_contract_balance_after VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  campaign_distributed_before VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  campaign_distributed_after VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  last_claim_at_after BIGINT UNSIGNED NULL,
  reward_claimed_event_json JSON NULL,
  reward_claimed_event_validated BOOLEAN NULL,
  receipt_json JSON NULL,
  status ENUM('PLANNED','SIGNED','BROADCAST','CONFIRMED','FAILED','PENDING_REVIEW','BLOCKED') NOT NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_message VARCHAR(512) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  signed_at TIMESTAMP(6) NULL,
  broadcast_at TIMESTAMP(6) NULL,
  confirmed_at TIMESTAMP(6) NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_reward_claim_jobs_job_id (job_id),
  UNIQUE KEY uq_reward_claim_jobs_authorization (authorization_job_id),
  UNIQUE KEY uq_reward_claim_jobs_reward_id (reward_id),
  KEY idx_reward_claim_jobs_wallet_id (wallet_id),
  KEY idx_reward_claim_jobs_status (status),
  KEY idx_reward_claim_jobs_signed_hash (signed_tx_hash),
  KEY idx_reward_claim_jobs_broadcast_hash (broadcast_tx_hash),
  CONSTRAINT fk_reward_claim_jobs_authorization
    FOREIGN KEY (authorization_job_id) REFERENCES reward_authorization_jobs (job_id),
  CONSTRAINT fk_reward_claim_jobs_wallet
    FOREIGN KEY (wallet_id) REFERENCES reward_user_wallets (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
