CREATE TABLE reward_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  chain_id INT UNSIGNED NOT NULL,
  campaign_operation_id BIGINT UNSIGNED NOT NULL,
  campaign_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  campaign_policy ENUM('FIRST_REWARD_ONLY','ONCE_PER_CAMPAIGN','RECURRING') NOT NULL,
  policy_scope VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_amount_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  dispatch_interval_seconds INT UNSIGNED NOT NULL,
  target_wallet_count INT UNSIGNED NOT NULL,
  processed_count INT UNSIGNED NOT NULL DEFAULT 0,
  confirmed_count INT UNSIGNED NOT NULL DEFAULT 0,
  already_rewarded_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  blocked_count INT UNSIGNED NOT NULL DEFAULT 0,
  reconciliation_required_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  transactions_sent INT UNSIGNED NOT NULL DEFAULT 0,
  total_reward_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '0',
  total_gas_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '0',
  current_sequence INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('DRAFT','READY','RUNNING','PAUSED','COMPLETED','COMPLETED_WITH_EXCEPTIONS','STOPPED','FAILED') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  started_at TIMESTAMP(6) NULL,
  paused_at TIMESTAMP(6) NULL,
  resumed_at TIMESTAMP(6) NULL,
  completed_at TIMESTAMP(6) NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_reward_runs_run_id (run_id),
  KEY idx_reward_runs_dispatch (status, campaign_operation_id, created_at),
  CONSTRAINT fk_reward_runs_campaign_operation FOREIGN KEY (campaign_operation_id) REFERENCES reward_campaign_operations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
