CREATE TABLE reward_run_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  sequence INT UNSIGNED NOT NULL,
  chain_id INT UNSIGNED NOT NULL,
  wallet_id BIGINT UNSIGNED NOT NULL,
  claimant_address CHAR(42) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  campaign_id CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  policy ENUM('FIRST_REWARD_ONLY','ONCE_PER_CAMPAIGN','RECURRING') NOT NULL,
  policy_scope VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_amount_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  authorization_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  claim_job_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  action VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  classification ENUM('PENDING','READY','SKIPPED','BLOCKED','RECONCILIATION_REQUIRED','CONFIRMED','FAILED','SYSTEM_ERROR') NOT NULL DEFAULT 'PENDING',
  lifecycle_state ENUM('PENDING','ACQUIRED','AUTHORIZED','SIGNED','BROADCAST','PENDING_REVIEW','FINALIZED') NOT NULL DEFAULT 'PENDING',
  transaction_hash CHAR(66) CHARACTER SET ascii COLLATE ascii_bin NULL,
  block_number BIGINT UNSIGNED NULL,
  reward_nonce VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  actual_gas_wei VARCHAR(78) CHARACTER SET ascii COLLATE ascii_bin NULL,
  blocker_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  started_at TIMESTAMP(6) NULL,
  completed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  first_reward_guard TINYINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN policy = 'FIRST_REWARD_ONLY' AND (classification IN ('PENDING','READY','CONFIRMED') OR lifecycle_state IN ('ACQUIRED','AUTHORIZED','SIGNED','BROADCAST','PENDING_REVIEW')) THEN 1 ELSE NULL END) STORED,
  once_campaign_guard TINYINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN policy = 'ONCE_PER_CAMPAIGN' AND (classification IN ('PENDING','READY','CONFIRMED') OR lifecycle_state IN ('ACQUIRED','AUTHORIZED','SIGNED','BROADCAST','PENDING_REVIEW')) THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_reward_run_items_run_sequence (run_id, sequence),
  UNIQUE KEY uq_reward_run_items_run_campaign_wallet (run_id, campaign_id, wallet_id),
  UNIQUE KEY uq_reward_run_items_first_reward (chain_id, policy_scope, claimant_address, first_reward_guard),
  UNIQUE KEY uq_reward_run_items_once_campaign (chain_id, campaign_id, claimant_address, once_campaign_guard),
  UNIQUE KEY uq_reward_run_items_authorization (authorization_job_id),
  UNIQUE KEY uq_reward_run_items_claim (claim_job_id),
  KEY idx_reward_run_items_next (run_id, classification, sequence),
  KEY idx_reward_run_items_claimant (chain_id, claimant_address),
  CONSTRAINT fk_reward_run_items_run FOREIGN KEY (run_id) REFERENCES reward_runs (run_id),
  CONSTRAINT fk_reward_run_items_wallet FOREIGN KEY (wallet_id) REFERENCES reward_user_wallets (id),
  CONSTRAINT fk_reward_run_items_authorization FOREIGN KEY (authorization_job_id) REFERENCES reward_authorization_jobs (job_id),
  CONSTRAINT fk_reward_run_items_claim FOREIGN KEY (claim_job_id) REFERENCES reward_claim_jobs (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
